name: Build Padavan Firmware

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        model: [ "MZJISU", "PSG1218", "K1", "MT7620", "MT7628" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget

      - name: Clone source code
        env:
          KERNEL: 3.4
        run: |
          if [ $KERNEL = "4.4" ] ; then
            git clone --depth=1 https://github.com/tengpeng1888/padavan-4.4.git /opt/rt-n56u
          else
            git clone --depth=1 https://github.com/tengpeng1888/rt-n56u.git /opt/rt-n56u
          fi
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh

      - name: Build Firmware (Per Model)
        env:
          TNAME: ${{ matrix.model }}
          KERNEL: 3.4
        run: |
          # 为每个型号创建独立的工作目录
          MODEL_DIR="/opt/build-${{ matrix.model }}"
          mkdir -p $MODEL_DIR
          # 复制源代码到独立目录（避免并发冲突）
          cp -r /opt/rt-n56u $MODEL_DIR/rt-n56u
          cd $MODEL_DIR/rt-n56u/trunk
          if [ ! -f configs/templates/$TNAME.config ] ; then
            echo "configs/templates/$TNAME.config not found"
            exit 1
          fi
          cp -f configs/templates/$TNAME.config .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME 0
          # 将生成的固件移动到全局目录（带唯一前缀）
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          sudo mkdir -p /opt/firmware-output
          sudo mv images/*.trx /opt/firmware-output/${TIMESTAMP}_$TNAME.trx

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Collect .trx files
        run: |
          sudo chmod -R 777 /opt/firmware-output
          ls -l /opt/firmware-output

      - name: Create ZIP
        id: create-zip
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          ZIP_NAME="padavan-all-models-${TIMESTAMP}.zip"
          cd /opt/firmware-output
          zip -j $ZIP_NAME *.trx
          echo "ZIP_PATH=/opt/firmware-output/$ZIP_NAME" >> $GITHUB_OUTPUT
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.create-zip.outputs.ZIP_NAME }}
          path: ${{ steps.create-zip.outputs.ZIP_PATH }}
